### ISSUE TITLE
Erweiterung um Temperatur und Feuchtesensor SHT21 / Si7021 

### ISSUE THREAD

**Issue by chianti2000** [pa-pa/AskSinPP#121]
Ist es dir möglich, den Temperatur- und Feuchtesensor SHT21 / Si7021 einzubinden. 
Er soll eine geringe Fehlertoleranz bei Feuchte aufweisen, wo der BME 280 ja etwas problematisch erscheint. Könnte dann mit dem BMP 280 arbeiten und den BME 280 ersetzen.

Viele Grüße Gerd

**Comment by jp112sdl** [comment]
**Wo** denn einbinden❓ 
Die Sensorklasse selbst gibts ja bereits...
https://github.com/pa-pa/AskSinPP/blob/master/sensors/Si7021.h

**Comment by jp112sdl** [comment]
Einen passenden Temperatursensor-Sketch gibt es auch:
https://github.com/jp112sdl/Beispiel_AskSinPP/tree/master/examples/HM-WDS40-TH-I-SI7021
