### ISSUE TITLE
Config Freq nach RESET gelöscht?

### ISSUE THREAD

**Issue by psi-4ward** [pa-pa/AskSinPP#130]
Bootlog **nachdem** zuvor FreqTest ausgeführt wurde:

```
AskSin++ V4.1.0 (Aug 26 2019 00:17:46)
Address Space: 32 - 1650
CC init1
CC Version: 14
 - ready
Config Freq: 0x21657A
ID: 010801  Serial: papa010801 debounce
 pressed
 longpressed
 longpressed
RESET
AskSin++ V4.1.0 (Aug 26 2019 00:17:46)
Address Space: 32 - 1650
00000000
Init Storage: CAFE6963
CC init1
CC Version: 14
 - ready
ID: 010801  Serial: papa010801
```

Nach dem `RESET` wird `Config Freq: 0x21657A` nicht mehr ausgegeben. Bedeutet dies, dass die Freqenzanpassung gelöscht ist? Afair sollte das in der Config-Area gespeichert sein und einen RESET überleben?

**Comment by psi-4ward** [comment]
Gibt es für dich Sinn, dass ein Adress-Space-Overflow den Config Bereich 0-28 beschädigt/überschreibt?

Flashe ich mit 2 Peers/Chan bekomme ich _Address Space: 32 - 870_ und nach einem RESET bleibt sc.valid() true und die Config-Freq wird wie erwartet ausgegeben.

**Comment by pa-pa** [comment]
Er berechnet wahrscheinlich irgendeine Mondchecksumme für den nicht existierenden Speicher. Das passt dann nicht mit der gespeicherten überein und als Fallback wird erst mal alles neu initialisiert :-)
