### ISSUE TITLE
Low-Bat.-Schwelle nur 5-15Volt

### ISSUE THREAD

**Issue by chkbln** [pa-pa/AskSinPP#154]
Hallo
ich nutze HM-LC-SW1-BA-PCB.ino und möchte die Hardware mit 2 Batterien betreiben.
also mit 3,3 Volt und niedriger. In der CCU2 lässt sich die Low-Bat.-Schwelle nur im Bereich 5-15Volt einstellen. Dadurch habe ich eine Fehlermeldung in der CCU und kann keine sinnvolle Warnung unter 3,3 Volt einstellen. Gibt es eine Möglichkeit das zu ändern? Wenn ja was müsste ich ändern?
Gruß
Christof

**Comment by jp112sdl** [comment]
Hi, schau mal hier:
https://homematic-forum.de/forum/viewtopic.php?f=76&t=54517#p542850

Einfach in der WebUI einen mit 3 multiplizierten Wert eingeben (bspw. 9V) und dann im Sketch / 3 dividieren, um 3V abzubilden.

**Comment by chkbln** [comment]
Hi
danke für Info. Das hat funktioniert.

Gruß
Christof

**Comment by pa-pa** [comment]
not really an issue
