### ISSUE TITLE
Dimmer: 'WORKING' state wird bei "heller/dunkler"-Steuerung mittels internem Peering nicht zurückgesetzt

### ISSUE THREAD

**Issue by jp112sdl** [pa-pa/AskSinPP#155]
Wird über das interne Peering (ConfigToggleButton) das Dimmlevel schrittweise erhöht/verringert, bleibt der Status "WORKING" in der CCU stehen.

Was ich bisher erfassen konnte:
**Steuerung über CCU:**
```

Empfange 5% Dimmlevel
-> 0E 0F A0 11 4A80E8 010801 02 01 0A 00 A0  - 12451
Ramp/Level: 50/10
Bestätige mit WORKING
<- 0F 0F 80 02 010801 4A80E8 01 01 00 50 24 00  - 12580
Beende WORKING
<- 0F 07 A2 10 010801 4A80E8 06 01 0A 00 24 0A  - 15060
Erhalte Quittung
-> 0A 07 80 02 4A80E8 010801 00  - 15185
waitAck: 01
```
_-> finaler Status ist korrekt._

**Steuerung über Taster, Funktion: "Dimmer heller":**
```
 debounce
 pressed
 released
-> 0B 08 02 40 010801 010801 01 08  - 88344

Neuer Dimmlevel wird an CCU gesendet inkl WORKING
<- 0F 09 A2 10 010801 4A80E8 06 01 14 20 26 14  - 90370

-> 0A 09 80 02 4A80E8 010801 00  - 90494
waitAck: 01
```
_-> WORKING bleibt bestehen._

**Steuerung über Taster, Funktion: "Dimmer ein":**
```
 debounce
 pressed
 released
-> 0B 10 02 40 010801 010801 01 10  - 343898
Ramp/Level: 50/200

Neuer Dimmlevel wird an CCU gesendet; alles i.O. - kein WORKING State
<- 0F 11 A2 10 010801 4A80E8 06 01 C8 00 28 C8  - 346529

-> 0A 11 80 02 4A80E8 010801 00  - 346654
waitAck: 01
```
_-> finaler Status ist korrekt._

**Comment by stan23** [comment]
Dieses Problem besteht immer noch:
in der CCU wird das Zahnrad angezeigt.

**Comment by stan23** [comment]
Der Grund ist dass bei der lokalen Bedienung der Wert `alarm.destlevel` nicht aktualisiert wird, und deswegen bei der Berechnung der Flags immer ein Delta erkannt wird:
https://github.com/pa-pa/AskSinPP/blob/master/Dimmer.h#L678L682
