### ISSUE TITLE
Pairing mit HM-Sec-Cen nicht möglich

### ISSUE THREAD

**Issue by darktransmission** [pa-pa/AskSinPP#175]
Hallo!

Leider lassen sich die nachgebauten Komponenten (u.a. HM-RC-P1) nicht an der Alarmzentrale (HM-Sec-Cen) anlernen. Habe auch die drei Zeilen mit #define aes ... versucht. Mit CCU2 oder Homegear gibt es keine Probleme. Ein Pairing mit einem originalen HM-PBI-4-FM oder HM-Sec-Mdir ist möglich.
Grüße,
Tobias

**Comment by pa-pa** [comment]
Pairing geht nur über die Centrale
