### ISSUE TITLE
AskSinPP-3 oder AskSInPP-4 als ZIP Bibliothek hinzufügen

### ISSUE THREAD

**Issue by JurgenO** [pa-pa/AskSinPP#183]
Hallo,

Das Hinzufügen der ZIP Bibliotheken AskSinPP-3 und AskSinPP-4 schlägt fehl: "Angegebener Ordner/ZIP-Datei enthält keine gültige Bibliothek" 

Ich nutze die Arduino-IDE Version 1.8.12. 

Das Hinzufügen der Bibliotheken AskSinPP-1, AskSinPP-2 sowie AskSin-Master funktioniert.

Kann mir jemand bitte ein Tipp geben woran das liegt oder was ich falsch mache ?

Gruss vom Niederrhein
Juergen

**Comment by stan23** [comment]
Wie hast du das ZIP denn runtergeladen?
Über diesen Link?
https://github.com/pa-pa/AskSinPP/archive/V4.zip

**Comment by JurgenO** [comment]
Hallo,
danke für die schnelle Antwort. Die Bibliothek über https://github.com/pa-pa/AskSinPP/archive/V4.zip hat die gleiche Fehlermeldung. Ich hatte den Branch V4 ausgewählt und dann die Datei heruntergeladen. Gibt es eine Möglichkeit dass mir die IDE sagt was genau das Problem ist ?

Gruss
Juergen

**Comment by stan23** [comment]
Auf den ersten Blick sehen die Archive für V4 und master gleich aus, und alle Branches waren mal der master bevor sie ausgebrancht wurden.

Du könntest ja von der installieren Lib den Inhalt mit dem der V4 austauschen.

**Comment by JurgenO** [comment]
Zwischenergebnis: durch "Try and Error" habe ich herausgefunden dass die Arduino IDE das AskSinPP-v4 ZIP Paket akzeptiert, wenn ich das enthaltene Verzeichnis "bootloader" lösche.

Der Master Branch AskSinPP-Master enthält auch ein bootloader Verzeichnis. Jetzt werde ich als nächstes untersuchen, worin sich die Verzeichnisse unterscheiden

**Comment by JurgenO** [comment]
Hallo nochmal.
Das AskSinPP-v4 ZIP Paket laesst sich als Bibliothek importieren wenn ich das Verzeichnis 
AskSinPP-4\bootloader\avr\srecord lösche.

ABER: 
Ich kann die AskSinPP-Master Bibliothek ohne Probleme einbinden, obwohl das auch das srecord Verzeichnis beinhaltet.

???

Merkwürdig. Mein Entwicklungsumgebung ist Win10 - das sollte doch kein Problem sein, oder ?

Gruss vom Niederrhein
Jürgen

**Comment by JurgenO** [comment]
Hallo, 

das Problem scheint das Laden über das Arduino Menu 
_Sketch > Bibliothek einbinden > .ZIP-Bibliothek hinzufügen_ zu sein.
Wenn ich ich die Bibliothek manuell einbinde wird sie erkannt & kann genutzt werden.

Deshalb denke ich, dass das ein Arduino IDE Problem ist und schliesse das Issue hier.

Gruss vom Niederrhein
Juergen
