### ISSUE TITLE
Bug beim ATmega328PB - OTA Adressen

### ISSUE THREAD

**Issue by TomMajor** [pa-pa/AskSinPP#208]
Beschäftige mich gerade etwas mit dem ATmega328PB und sehe durch Zufall in Device.h, in dieser Zeile
https://github.com/pa-pa/AskSinPP/blob/master/Device.h#L29
Ist das
`|| defined(__AVR_ATmega328PB__)`
am Ende der Zeile ein Bug, oder?
Weil der ATmega328PB ja auch nur 32k hat, dann wären die 0xffxx OTA Adressen invalid.

**Comment by pa-pa** [comment]
gefixt
