### ISSUE TITLE
how is it possible to use the AskSinPP libary with the original trx-868 RF module

### ISSUE THREAD

**Issue by v0r73x** [pa-pa/AskSinPP#210]
Hi,

Is it possible to use the EQ3 RF modules (trx868-TFK-TI or trx868-SL) instead of the cc1101 rf module?
If yes, how i can do that? 

thanks for your feedback,

v0r73x

**Comment by jp112sdl** [comment]
Hi,
yes it is possible.
wiring is explained here: https://wiki.fhem.de/wiki/HomeMatic_Asksin_Library

**Comment by v0r73x** [comment]
i cabeled it already and tested it but i see only the CC init and that is all ;(

**Comment by v0r73x** [comment]
![image](https://user-images.githubusercontent.com/48632087/96265056-42e1cb80-0fc5-11eb-90ac-be392c5024f4.png)

and cabeling as described on the page you given. 
I tried with the freq test first to check the module before starting to attach sensors etc.

**Comment by jp112sdl** [comment]
Can you attach a picture of your cabling?

**Comment by v0r73x** [comment]
![Uploading AEBB7EEC-3685-4884-BCCE-F6BEE5284A66.jpeg…]()

**Comment by v0r73x** [comment]
![2F60A3CC-DFE3-4F04-9630-93027A192ECF](https://user-images.githubusercontent.com/48632087/96272658-b20fed80-0fce-11eb-8cd3-c4e5227f8197.jpeg)

**Comment by v0r73x** [comment]
![Uploading 81D9E348-18B0-49A2-8BCF-4BE6CCDDCAE8.jpeg…]()

**Comment by v0r73x** [comment]
![image](https://user-images.githubusercontent.com/48632087/96273064-34001680-0fcf-11eb-821e-c8e7ddb61694.jpg)

**Comment by v0r73x** [comment]
![image](https://user-images.githubusercontent.com/48632087/96273348-87726480-0fcf-11eb-8da3-ed89b8096cdb.jpg)

**Comment by v0r73x** [comment]
von links nach rechts

trx868 PIN1 = rot an GPIO 11
trx868 PIN2 = sw  an GPIO 13
trx868 PIN3 = lila an GPIO 12
trx868 PIN4 = frei 
trx868 PIN5 = blau an GPIO 2
trx868 PIN6 = grün an GPIO 10
trx868 PIN7 = gelb an GPIO GND
trx868 PIN8 = braun an GPIO VCC

**Comment by jp112sdl** [comment]
Hmm, ja alles richtig.

Was passiert wenn du die SPI-Pins (11 und 12) trennst?
Startet der Pro Mini dann weiter? Es sollten dann zumindest jede Menge Read-Error kommen

**Comment by v0r73x** [comment]
ja er startet und auch die errors kommen wenn ich PIN 11 & 12 abziehe

**Comment by v0r73x** [comment]
![image](https://user-images.githubusercontent.com/48632087/96282272-cbb73200-0fda-11eb-8ebb-05ae4a23d17c.png)

**Comment by jp112sdl** [comment]
Hat vielleicht doch das Funkmodul einen weg?
Ich vermute mal, dass es bei angeschlossenem Funkmodul an [`waitMiso ()`](https://github.com/pa-pa/AskSinPP/blob/0f3dad518f8bed6f40353473111e06c0f73f52b2/Radio.h#L181) hängt.

**Comment by v0r73x** [comment]
Hi Jerome, und alle anderen die mitlesen ;) 

ich habe es jetzt mit einem komplett anderen TRX868 probiert - nun ist der output gleich von begin Fehlerhaft nachdem ich das FreqTest sketch geflashed habe ... kabel sind aber richtig angeschlossen nr PIN 4 vom trx868 habe ich freigelassen 

![image](https://user-images.githubusercontent.com/48632087/96412138-ead7de80-11e9-11eb-8cf3-9a352769a98b.png)

**Comment by v0r73x** [comment]
Muss ich vielleicht noch etwas im code anpassen damit das trx868 funktioniert?

**Comment by v0r73x** [comment]
Ich habe auch die Kabel gekürzt beim anderen trx868 Modul
![image](https://user-images.githubusercontent.com/48632087/96412907-1b6c4800-11eb-11eb-8849-d5ce6204f400.jpg)

**Comment by jp112sdl** [comment]
> Muss ich vielleicht noch etwas im code anpassen damit das trx868 funktioniert?

Nein, ich nutze es auch seit Jahren ohne irgendwelche Mods

Ähm... ist das ein TRX868**-TI** oder **-SL** ?

Das **-SL** funktioniert **nicht** mit der AskSinPP. Es besitzt keinen CC1101 Chip!

**Comment by jp112sdl** [comment]
Ah, ich sehe etwas unscharf auf dem Foto weiter oben... das ist -SL
Dann brauchst du es nicht weiter versuchen

**Comment by v0r73x** [comment]
Ach mist - ok ich habe schon an meinen löt kenntnissen gezweifelt ;) So richtig geht das aber aus der Beschreibung auf https://wiki.fhem.de/wiki/HomeMatic_Asksin_Library nicht hervor, da die "nur" vom breiten und vom schmalen modul sprechen...

**Comment by v0r73x** [comment]
Ich habe noch ein Modul gefunden denkst Du das könnte gehen?
![image](https://user-images.githubusercontent.com/48632087/96423658-ed423480-11f9-11eb-9a19-7c5bc16ff68a.jpg)

**Comment by jp112sdl** [comment]
Dort steht `-TI`
Die Frage solltest du dir somit beantworten können.

**Comment by v0r73x** [comment]
ja aber das TFK hat mich jetzt irritiert - ok ich versuche es jetzt damit nochmal

**Comment by jp112sdl** [comment]
Nur noch mal der Vollständigkeit halber: 
Es gibt beide Modulausführungen (breit und schmal) mit Funkchip von Texas Instruments (`-TI`) und SiliconLabs (`-SL`).
Das breite Modul geht daher prinzipiell auch, sofern es sich um ein `-TI` handelt.

![Bild](https://user-images.githubusercontent.com/18190139/96430202-2a122980-1202-11eb-9dd0-9a8a0f211d6e.jpeg)

@stan23 Hattest du nicht auch mal irgendwo einen Beitrag zu den beiden Modultypen geschrieben?

**Comment by TomMajor** [comment]
Ich kann die Info im FHEM Wiki ergänzen.
Gibt es eigentlich HM Geräte die immer die -TI bzw. -SL haben oder kann man das vorher nicht sagen bevor man es nicht geöffnet/ausgelötet hat?

**Comment by stan23** [comment]
> 
> @stan23 Hattest du nicht auch mal irgendwo einen Beitrag zu den beiden Modultypen geschrieben?

Hier steht was kurzes:
https://homematic-forum.de/forum/viewtopic.php?f=76&t=59292&p=587278&hilit=SiLabs#p587276

Angeschaut habe ich das im Zuge der WoR-Analyze, kann mich aber nicht erinnern ob ich das noch detaillierter dokumentiert habe.

**Comment by v0r73x** [comment]
Hi TomMajor, 
ich habe die Beiden TRX868-SL auf dem Aktor: HM-LC-Sw4-Ba-PCB gefunden. 
Beide HM-LC-Sw4-Ba-PCB wurden als defekt verkauft, aber ich dachte ich kann den Funkmodulen nochmal ein neues Leben einhauchen für einen Homebrew Aktor - Schade ;(

**Comment by jp112sdl** [comment]
> Gibt es eigentlich HM Geräte die immer die -TI bzw. -SL haben oder kann man das vorher nicht sagen bevor man es nicht geöffnet/ausgelötet hat?

Innerhalb eines Gerätetyps ist das Modul identisch. Der HM-LC-Sw4-Ba-PCB hat dann also immer ein `-SL` verbaut.

In manchen Bauanleitungen steht es detailliert drin, welches Modul verbaut ist, in anderen wiederum nur allgemein "TRX868".

Hier mal was ich auf die Schnelle zusammentragen konnte:
|Gerät|Modul|
|------|------|
|HM-SenDB-PCB|TRX868-SL|
|HM-ES-TX-WM|TRX868-SL|
|HM-Dis-WM55|TRX868-TFK-SL|
|HM-PB-2-FM|TRX868-TFK-SL|
|HM-TC-IT-WM-W-EU|TRX868-TFK-SL|
|HM-CC-RT-DN|TRX868-TFK-SL|
|HM-Sec-SCo|TRX868-TFK-SL|
|HM-RC-2-PBU-FM|TRX868-TFK-SL|
|HM-Sen-MDIR-O|TRX868-TFK-TI|
|HM-SCI-3-FM|TRX868-TFK-TI|
|HM-LC-Sw1-BA-PCB|TRX868-TI|
|HM-OU-CFM-TW|TRX1-TIF|
|HM-LC-Sw1-PLl-DN-R1|TRX1-TIF|
|HM-Dis-EP-WM55|TRX2-TIF|
|HM-LC-Sw2PBU-FM|TRX2-TIF|
|HM-LC-RGBW-WM|TRX3-TIF|


Bei den Bezeichnungen TRX _n_-TIF weiß ich nicht, was genau an Hardware drin steckt.
Ich gehe von einem CC1101 aus... aber ich glaub die 3. Gen. (TRX3) wird auch bei den HmIP-Geräten verwendet und beherbergt ein CC1310? Nur eine vage Vermutung.

**Comment by TomMajor** [comment]
Sehr interessant, danke euch Jerome und v0r73x für die Infos zu den Funkchips in HM Geräten.

Ich habe einen Hinweis im wiki ergänzt, neuer Abschnitt **Achtung, verschiedene Funkchips**
https://wiki.fhem.de/wiki/HomeMatic_Asksin_Library

**Comment by jp112sdl** [comment]
> Ich habe einen Hinweis im wiki ergänzt

Sehr gut!
_Eigentlich komisch, dass das Thema bisher nie aufkam. Das `-SL` ist ja doch sehr verbreitet_

**Comment by v0r73x** [comment]
scheinbar basteln viele nur nach und probieren nicht kaputte aktoren zu upcyclen wie ich ;) 

@TomMajor besten dank für das Einpflegen ins wiki :) 

OFFTOPIC ich werde jetzt tiefer in die HomeBrew Thematik einsteigen - Ich würde gern den HB-UNI-RGB-LED-CTRL 
mit einem ds18b20 temp fühler austatten wollen da der im wohnzimmer hängt - @jp & all others: ist das generell möglich ?

**Comment by jp112sdl** [comment]
Mach für allgemeine Diskussionen bitte einen neuen Thread im Homematic Forum auf
https://homematic-forum.de/forum/viewforum.php?f=76

Um es vorweg zu nehmen - ja es ist technisch möglich. Aber der Aufwand, es in die CCU zu integrieren, lohnt nicht. +Nimm am besten 2 einzelne Geräte

**Comment by TomMajor** [comment]
Gerne.
Und noch ein Hinweis für @v0r73x 
Du solltest die github Namen exakt schreiben mit @
Momentan referenzierst du Julien Pellet in Montreal.
