### ISSUE TITLE
Vorgehensweise bei Änderungen

### ISSUE THREAD

**Issue by jp112sdl** [pa-pa/AskSinPP#230]
Hallo zusammen
@pa-pa @trilu2000 

Da nun hier mehrere Leute direkten Schreibzugriff haben, hätte ich vorgeschlagen, dass Änderungen vielleicht erst in einem PR verfasst (oder einem extra Branch) werden und dieser dann (gern auch selbstständig) erst nach **erfolgreichem** Travis-Lauf (der ja automatisch startet) merged wird.

Diese Änderung führt aktuell dazu, dass einige Projekte nicht mehr kompilieren:
https://github.com/pa-pa/AskSinPP/blame/0b8ffaa5f6ce9c40c66356aae7fccbd89f1d1291/Peer.h#L21

Das würde dann vielleicht eher auffallen und somit wäre dann der master-Branch erstmal nicht "kaputt".

**Comment by pa-pa** [comment]
Bin im Prinzip auch dafür - wollt @trilu2000 das Leben etwas einfacher machen.
Ich Push ja auch immer direkt.

**Comment by trilu2000** [comment]
Ihr müsst mir bitte erklären wie ich mein Zeug hochladen soll. 
Bei mir kompiliert das ja, sonst würde ich es nicht hochladen.
Seit dem letzten Problem mit den überschneidenden Variablennamen kompiliere ich 2 oder 3 verschiedene Sketches auf Basis AVR vorher.

**Comment by jp112sdl** [comment]
> Bei mir kompiliert das ja, sonst würde ich es nicht hochladen.

Hmm... aktuell gehen laut Travis 15 Projekte nicht mehr

> Ich Push ja auch immer direkt.

Ist ja auch dein Repo 😎 

Ich hab ja anfangs auch direkt gepusht, aber es gab halt auch oft noch Nacharbeiten, nach Austausch und Diskussionen.
Diese Änderungen dann alle in einem finalen PR zusammengefasst machen die Gesamtstruktur übersichtlicher und nachvollziehbarer.

**Comment by trilu2000** [comment]
und was mache ich jetzt?
kann ich den Commit zurück nehmen?

Um einen PR zu machen muss ich wieder einen eigenen fork machen, gegen den mache ich meine Änderungen und dann per PR in den master pushen?

**Comment by jp112sdl** [comment]
@pa-pa hat einen fix gepusht, aktuell sieht es gut aus. 
Travis baut aber momemtan noch

**Comment by jp112sdl** [comment]
@trilu2000 Du kannst auch hier direkt in einen neuen Branch pushen (nennst ihn _trilu_dev_ oder so) und diesen Branch kannst du dann in den master mergen.

**Comment by stan23** [comment]
> 
> Um einen PR zu machen muss ich wieder einen eigenen fork machen, gegen den mache ich meine Änderungen und dann per PR in den master pushen?

Github Desktop bietet das inzwischen an. Man kann das Haupt-Repo für Pulls nehmen, und in einen eigenen Fork pushen und dann einen PR stellen. Oder man macht das per Hand über die Kommandozeile.

Gerade wenn mehrere an einem Projekt arbeiten, sind eigene Branches (auf denen dann die Tests laufen und vor dem Merge ein Review gemacht wird) state of the art, oder?

**Comment by jp112sdl** [comment]
Ich mach das alles bequem mit Sourcetree (https://www.sourcetreeapp.com). Kann ich uneingeschränkt empfehlen.
Gibt es für Win und Mac

**Comment by TomMajor** [comment]
> Gerade wenn mehrere an einem Projekt arbeiten, sind eigene Branches (auf denen dann die Tests laufen und vor dem Merge ein Review gemacht wird) state of the art, oder?

Finde ich auch. Momentan hängen sehr viele HB Projekte am master branch. Ein develop branch mit Tests und idealerweise review nach 4-Augen Prinzip ist gängige Praxis.

**Comment by pa-pa** [comment]
Deshalb hatte ich ja bisher immer die V(1|2|3|4)-Branches, damit ich den Master auch mal kaputt machen kann :-)
Aber die hat wahrscheinlich eh niemand wirklich genommen. 
Bei allen "schönen" Dev-Workflows (ich könnte da auch noch einiges reinwerfen) müssen wir aber sicherstellen, dass es noch zeitlich machbar ist. Ich wollte (wenn möglich) es erst mal einfach halten.

**Comment by jp112sdl** [comment]
> Ich wollte (wenn möglich) es erst mal einfach halten.

Das wäre es doch mit Branches direkt hier, wie erst kürzlich mit dem "optimize"?

Das Problem mit den V-Branches ist, dass sie (nur) mit "älteren" Projekten funktionieren.

Änderungen im master erfolgen ja meist, um ein aktuelles Projekt lauffähig zu bekommen.

Und dann verweise ich auch in der Anleitung zum Projekt, zwingend den master-Branch zu verwenden.
Ich könnte auch auf einen bestimmten Commit verweisen, mit dem das jeweilige Projekt garantiert funktioniert. Das macht jedoch das Handling für Nachbauer schwieriger

Alternativ könnte ich bei meinen Projekten auf die Verwendung meines Forks verweisen.
Und den aktualisiere in unregelmäßigen Abständen oder nur bei Bedarf (nach vorheriger Travis-Prüfung).

**Comment by pa-pa** [comment]
Extra-Fork fände ich eher schlecht. Habe Euch ja den Zugriff nicht gegeben, damit dann noch eine Kopie gepflegt werden muss.
Aber ich habe lieber ein aktives Projekt, wo dann sicherlich auch mal was kaputt geht, als wenn nicht passiert.
Jetzt wird die Lib ja auch über Arduino-Manager ausgeliefert. Vielleicht schafft das ja etwas "Luft", da ja nicht jede Änderung in der Lib zu einer neuen Version führt. Wir müssten dann halt sehen, das wichtige Anpassungen "zeitnah" als Version getaggt werden, damit der Library-Manager aktualisiert wird. Spricht natürlich auch wieder für Dev-Branches, wenn umfangreichere Änderungen vorgenommen werden.

**Comment by TomMajor** [comment]
ich verweise auch wie Jerome teilweise auf den master Branch, die V4 ist ja relativ alt.
> Der HB-UNI-Sensor1 Sketch benötigt den master-Branch der AskSinPP Library, nicht den V4 Release-Branch wie dort angegeben. Grund: Verwendung der broadcastEvent() Methode.

IMHO ist es gängige und erwartete Praxis vieler github Projekte, das der master ein stabiler und verwendbarer branch ist.
Kleine überschaubare Änderungen kann man sicher direkt darin commiten.
Größere Änderungen wie ein neuer HW support sollten in einem dev branch fertig entwickelt werden, travis, gut getestet, review usw. und dann erst gemergt werden - just my 2ct.

**Comment by jp112sdl** [comment]
Es ist ja nicht so, dass hier jeden zweiten Tag Änderungen einfließen.

Also letztendlich ging es mir hauptsächlich darum, Änderungen erstmal in einem extra Branch (egal ob im eigenen Fork oder direkt hier) durch den Travis laufen zu lassen, statt das direkt im Master machen zu lassen.

Ich war total verunsichert, weil ich die Änderung in der `Activity.h` genau aus dem Grund des vorherigen Travis-Run nicht direkt in den master gepusht habe. Der erste Versuch schlug auch tatsächlich fehl. Hab dann nachgebessert. Travis war ok.
Dann hab ich gemerged.
Ein paar Minuten später kam die Mail von Travis, dass es wieder Probleme gibt.
Und ich fing an, den Fehler bei mir und meinem Commit zu suchen.
Dass Trilu just in der kurzen Zeit was direkt in den master gepusht hatte, hab ich so schnell gar nicht realisiert.

@TomMajor Die V5 ist mittlerweile am nächsten dran am Master und hat auch `broadcastEvent`.

**Comment by trilu2000** [comment]
Mir erscheint das mit dem 4 Augen Prinzip als nicht praktikabel, wer würde denn die Änderungen anschauen und final beurteilen?
Ich versuche mein Zeug ab sofort in einen eigenen Branch zu packen und als PR zu beschreiben - scheint ja als wären meine commits immer wieder der Grund des Problems...

**Comment by jp112sdl** [comment]
Meine Commits funktionieren auch <strike>nicht immer</strike> nur selten auf Anhieb, wie z.B. hier bei mir heut früh:
<img width="873" alt="Bildschirmfoto 2021-02-07 um 17 47 32" src="https://user-images.githubusercontent.com/18190139/107153211-901aec00-696c-11eb-8050-1319ec9c41ee.png">


Durch den PR (oder extra Branch hier) sieht man erstmal ob Travis noch alles bauen kann (derzeit werden **94 Sketche** geprüft!)

Wenn nicht - muss nachgebessert werden.
Ist der Haken grün, kann gemerged werden.

**Comment by trilu2000** [comment]
falls jemand nach dem 4 Augen Prinzip kontrollieren möchte...
Simulated keypress implementation #232

**Comment by jp112sdl** [comment]
Cool. Funktioniert das jetzt automatisch mit allen Aktor-Sketchen (Switch, Blind, Dimmer)?

**Comment by trilu2000** [comment]
Momentan funktioniert das nur beim Dimmer - ich würde das aber in Switch und Blind einbauen, sobald ich wieder mal so ein Device brauche.

**Comment by pa-pa** [comment]
Wieso funktioniert das nur im Dimmer ? Das ist doch alles in der Standard process() Methode.

**Comment by jp112sdl** [comment]
Ich hab mal noch die README um `NDEBUG` und `HIDE_IGNORE_MSG` ergänzt

**Comment by trilu2000** [comment]
@papa, Du hast recht, ich habe das mit dem power-up flag verwechselt, das ist nur im Dimmer implementiert.

**Comment by pa-pa** [comment]
können wir jetzt zu machen
