### ISSUE TITLE
Dimmer.h setTemperature() should use signed variables

### ISSUE THREAD

**Issue by stan23** [pa-pa/AskSinPP#241]
https://github.com/pa-pa/AskSinPP/blob/master/Dimmer.h#L981

The over-temperature detection breaks for negative temperatures. This happened tonight in my garage.

**Comment by stan23** [comment]
Okay, da war ich wohl zu langsam bzw. habe zu lange auf HW getestet...

**Comment by pa-pa** [comment]
Ich habs nicht wirklich getestet - sollte aber gehen. Kannst ja mal rückmelden.

**Comment by stan23** [comment]
Ich hab den Code mehrfach instrumentiert und sich ändernde Faketemperaturen benutzt.
Die jetzige Lösung (durchgängig int16) funktioniert für alle Fälle.

**Comment by pa-pa** [comment]
Super -danke
