### ISSUE TITLE
HM-ES-TX-WM: gas counter increases continuosly even if no input

### ISSUE THREAD

**Issue by soosp** [pa-pa/AskSinPP#310]
I tested HM-ES-TX-WM example configured as gas meter in the CCU. There was a reed switch attached to the Arduino pin 14 with proper pull up. When a magnet was approached to the reed switch the counter on the serial debug output displayed and increased properly. But the input in first reporting period wasn't displayed by CCU. From the second period the counter on CCU increases continuosly period by period even if no input.

**Comment by JurgenO** [comment]
Hi,
it worked for me. Are you sure you have connected A0 ? 
Please see my project description: https://github.com/JurgenO/GasMetering/wiki/%2303:-Build-the-hardware

**Comment by soosp** [comment]
Yes, sure. It tesetd with reed switch and with pure contact only. It seems to be a software problem. If there is no input, the counter remains zero. But if a pulse arrives, the counter starts to incease.

**Comment by soosp** [comment]
![HM-ES-TX-WM](https://user-images.githubusercontent.com/24782682/223225607-e92a7327-455f-4e4d-87ea-82fcc12df839.jpg)

As you can see, only one pulse has arrived, the ratio is 0.01 m3/pulse, and after two periods the counter shows 0.002 m3. The counter was reseted before this test.

**Comment by soosp** [comment]
![HM-ES-TX-WM_2](https://user-images.githubusercontent.com/24782682/223226667-e318222c-964c-435e-ac67-a79f532b0093.jpg)

Some minutes later...

**Comment by jp112sdl** [comment]
Afaik, the 2-channel version in this repository only works correctly with FHEM.

For a ccu, I made a "1-channel only" version of the sketch:
https://github.com/jp112sdl/Beispiel_AskSinPP/blob/master/examples/HM-ES-TX-WM_CCU/HM-ES-TX-WM_CCU.ino

Give it a try...

**Comment by soosp** [comment]
Thanks for the idea! It works with my CCU/RaspberryMatic. Only the Consumption value is strange for me. How is it calculated?

**Comment by soosp** [comment]
Meanwhile I got that consumption unit is wrong in CCU. It should be m³/h.
