### ISSUE TITLE
Ignore repeated message

### ISSUE THREAD

**Issue by jp112sdl** [pa-pa/AskSinPP#316]
@pa-pa @trilu2000 

Mir war da gestern Abend in unserem Meeting noch was aufgefallen:
https://github.com/pa-pa/AskSinPP/blob/b83fd61f09f9a964eba8095ac5c5535606563b10/MultiChannelDevice.h#L247-L251

Das ist meiner Meinung nach falsch.
Hier wird nicht nur geprüft, ob die empfangene Meldung identisch zum vorherigen Absender+Counter ist, sondern auch ob `msg.isRepeated()` gesetzt ist.

Dieses Flag setzt afaik nur der Repeater (HM-Sys-sRP-Pl) und ist auch nur für diesen "interessant", um Endlosschleifen zu vermeiden.

https://github.com/pa-pa/AskSinPP/blob/b83fd61f09f9a964eba8095ac5c5535606563b10/Message.h#L63-L64

Also vom Flow her, wie ich es verstehe: 
Ein Gerät sendet eine Message mit `RPTEN`. Ein Repeater empfängt eine solche Message und erkennt, dass diese Nachricht überhaupt repeated werden darf. Anschließend wird von diesem das `RPTED` Flag angehängt, damit das Telegram nicht durch einen zweiten Repeater nochmals ausgesendet wird.

**Gibt es gegenteilige Meinungen, `msg.isRepeated()` aus der Bedingungsprüfung zu entfernen?**

_Ich glaub, das ist auch der Bug, der bei mir manchmal Aktoren mit verknüpftem Toggle-Fernbedienungstaster kurz ein und wieder aus schaltet. Es liegt wohl einfach nur daran, dass dann mehrfach gesendet._

**Comment by trilu2000** [comment]
Hi Jerome,

Du hast recht, es ist ja völlig egal ob das repeated flag gesetzt ist oder nicht.

Eine wiederholte Nachricht bleibt eine wiederholte Nachricht und muss nicht noch einmal ausgeführt werden.

Einzig, es darf keinen Repeater Sketch geben 😊

Viele Grüße

Horst

 

 

Von: Jérôme ***@***.***> 
Gesendet: Dienstag, 16. Januar 2024 07:24
An: pa-pa/AskSinPP ***@***.***>
Cc: trilu2000 ***@***.***>; Mention ***@***.***>
Betreff: [pa-pa/AskSinPP] Ignore repeated message (Issue #316)

 

@pa-pa <https://github.com/pa-pa>  @trilu2000 <https://github.com/trilu2000> 

Mir war da gestern Abend in unserem Meeting noch was aufgefallen:
https://github.com/pa-pa/AskSinPP/blob/b83fd61f09f9a964eba8095ac5c5535606563b10/MultiChannelDevice.h#L247-L251

Das ist meiner Meinung nach falsch.
Hier wird nicht nur geprüft, ob die empfangene Meldung identisch zum vorherigen Absender+Counter ist, sondern auch ob msg.isRepeated() gesetzt ist.

Dieses Flag setzt afaik nur der Repeater (HM-Sys-sRP-Pl) und ist auch nur für diesen "interessant", um Endlosschleifen zu vermeiden.

https://github.com/pa-pa/AskSinPP/blob/b83fd61f09f9a964eba8095ac5c5535606563b10/Message.h#L63-L64

Also vom Flow her, wie ich es verstehe:
Ein Gerät sendet eine Message mit RPTEN. Ein Repeater empfängt eine solche Message und erkennt, dass diese Nachricht überhaupt repeated werden darf. Anschließend wird von diesem das RPTED Flag angehängt, damit das Telegram nicht durch einen zweiten Repeater nochmals ausgesendet wird.

Gibt es gegenteilige Meinungen, msg.isRepeated() aus der Bedingungsprüfung zu entfernen?

Ich glaub, das ist auch der Bug, der bei mir manchmal Aktoren mit verknüpftem Toggle-Fernbedienungstaster kurz ein und wieder aus schaltet. Es liegt wohl einfach nur daran, dass dann mehrfach gesendet.

**Comment by pa-pa** [comment]
👍

**Comment by jp112sdl** [comment]
> Einzig, es darf keinen Repeater Sketch geben 😊

Doch, den gibt es :)
https://github.com/jp112sdl/Beispiel_AskSinPP/blob/master/examples/HM-Sys-sRP-Pl/HM-Sys-sRP-Pl.ino

Aber auch da ist es kein Problem, da Nachrichten, außer Config, nie an ihn adressiert sind. Der "hört" ja nur mit.
