### ISSUE TITLE
RESET nicht möglich

### ISSUE THREAD

**Issue by jp112sdl** [pa-pa/AskSinPP#33]
Hi! :)

Seit Commit 923fe6b wird nach einem länger gedrücktem "longpressed" kein RESET mehr ausgelöst.

Vor 923fe6b:
<img width="304" alt="bildschirmfoto 2018-03-30 um 18 32 34" src="https://user-images.githubusercontent.com/18190139/38145390-50b85418-3449-11e8-98cc-8ba4db19a8e8.png">

Ab 923fe6b:
<img width="184" alt="bildschirmfoto 2018-03-30 um 18 33 35" src="https://user-images.githubusercontent.com/18190139/38145401-5b72f91c-3449-11e8-878c-cbc82f84e005.png">

**Comment by TomMajor** [comment]
kann ich bestätigen, mit aktuellem Stand auf Branch master kommt kein Reset nach longpressed mehr.

**Comment by pa-pa** [comment]
War fälschlicherweise auskommentiert. Hatte mich gestört, da mein STM32 code immer einen Reset gemacht hat, wenn der Config-Button kurz gedrückt wurde :-(
Ist wieder geändert.
