### ISSUE TITLE
Dimmer for dualwhite

### ISSUE THREAD

**Issue by howy075** [pa-pa/AskSinPP#40]
Hello, could you perhaps integrate the actuator HM-LC-DW-WM?
greetings
Harald

**Comment by pa-pa** [comment]
I currently have no plan to do it. May be if I have a lot of free time.

**Comment by pa-pa** [comment]
HM-LC-DW-WM added for STM32

**Comment by psi-4ward** [comment]
I've constructed a LC-DW with an Arduino and used `{0x01,0x08}` as Model.
The CCU shows it correctly but usage of the Channels is wrong.

**Actual:**
Chan 1 controls LED1
Chan 2 controls LED2

**Expected:**
Chan 1 controls the brightness
Chan 2 controls the color temperature

![crossfade_linear_konstant_niedrigistwarm](https://user-images.githubusercontent.com/1191572/53699896-44a94c00-3ded-11e9-81e1-d5dd795da93d.png)


Another thing: I could not find/configure the on/off ramp times.

**Comment by pa-pa** [comment]
Oh - the example is an HM-DW-WM - 2 channel dimmer. Can you please share your hardware setup and current code. The physical dimmer behavior can be changed by replace the DimmerControl class. Because the channels have different registers the channel configuration of the device needs also changed.

**Comment by psi-4ward** [comment]
Thx for your fast answer.

The sketch is basically the same as your `HM-DW-WM.ino` expect the temperature and encoder stuff:

```cpp
#define EI_NOTEXTERNAL
#include <EnableInterrupt.h>
#include <AskSinPP.h>
#include <LowPower.h>

#include <Dimmer.h>
#include <DwDimmerChannel.h>

#define LED_PIN 4
#define CONFIG_BUTTON_PIN 8
#define DIMMER1_PIN 3
#define DIMMER2_PIN 5

#define PEERS_PER_CHANNEL 4
using namespace as;

// define all device properties
const struct DeviceInfo PROGMEM devinfo = {
    {0x01,0x08,0x01},       // Device ID
    "PsiDimDW01",           // Device Serial
    {0x01,0x08},            // Device Model (0x08: DualWhite; 0x09: 2-Ch)
    0x29C,                  // Firmware Version
    as::DeviceType::Dimmer, // Device Type
    {0x01,0x00}             // Info Bytes
};

typedef AvrSPI<10,11,12,13> SPIType;
typedef Radio<SPIType,2> RadioType;
typedef StatusLed<LED_PIN> LedType;
typedef AskSin<LedType,NoBattery,RadioType> HalType;
typedef DimmerChannel<HalType,PEERS_PER_CHANNEL> ChannelType;
typedef DimmerDevice<HalType,ChannelType,6,3> DimmerType;

HalType hal;
DimmerType sdev(devinfo,0x20);
DimmerControl<HalType,DimmerType,PWM8<> > control(sdev);
ConfigToggleButton<DimmerType> cfgBtn(sdev);

void setup () {
  DINIT(57600,ASKSIN_PLUS_PLUS_IDENTIFIER);
  if( control.init(hal,DIMMER1_PIN,DIMMER2_PIN) ) {
    sdev.channel(1).peer(cfgBtn.peer());
    sdev.channel(3).peer(cfgBtn.peer());
  }
  buttonISR(cfgBtn,CONFIG_BUTTON_PIN);
  sdev.initDone();
  sdev.led().invert(true);
  DDEVINFO(sdev);
}

void loop() {
  hal.runready();
  sdev.pollRadio();
}
```

And the Hardware is like https://asksinpp.de/assets/img/HM-LC-Dim1PWM.a394426a.svg
with a second MOSFET connected on PIN 5.

So we need to adjust both outputs every time a signal comes for Ch1 or Ch2:
Assumed Ch2 value is 50%. When we set the value of Ch1 to 100% both LEDs should be fully on.
If Ch2 value is 100% and Ch1 is 100% only the cold-white LED should glow.

Jerome pointed me to extend the `DimmerChannel` and add some custom `process()` implementations but I didn't try it yet.

**Comment by pa-pa** [comment]
Can you please replace the DimmerControl by the new DualWhiteControl class in your code. This should use Ch1 for the brightness and Ch2 for the color adjustment.

**Comment by psi-4ward** [comment]
It works! But probably we should better adjust the calculation to this to be able to power both LEDs with 100% at the same time:

![crossfade_linear_maximal_niedrigistkalt](https://user-images.githubusercontent.com/1191572/53759668-2e6cc000-3ec1-11e9-8a4c-540303deb689.png)

![screenshot-2019-03-04_21-06](https://user-images.githubusercontent.com/1191572/53759758-607e2200-3ec1-11e9-9568-8f36d1fbc4f2.png)

**Comment by pa-pa** [comment]
Better now ?

**Comment by psi-4ward** [comment]
You're the mastmind! 
Works like a charm! Thx!! :+1: 

**For the record**  
It implements the linear crossfade with no pegel-limit.  
Cubic, Dim2Hot and Dim2Cold settings are ignored.


Commits: d4c06289ca3f6682fa00173f750f77b8922449fd, 01351065cfdf6a222e061a33f400cb8e5e4d4f10

**Comment by psi-4ward** [comment]
Should we push the `HM-LC-DW_2Ch.ino` and `HM-LC-DW_DualWhite.ino` in the arduino version to the examples folder? I could prepare a PR for this.

**Comment by pa-pa** [comment]
Yes, but we should use the "normal" HM names - HM-DW-WM & HM-LC-DW-WM

**Comment by psi-4ward** [comment]
Hmm but the selling name is HM-DW-WM but the CCU lables it as HM-LC-DW-WM.
The original has a hardware switch to choose between 2-Ch and DualWhite mode.

**Comment by pa-pa** [comment]
This strange - there are two different XML files

https://asksinpp.de/rftypes/rf_dim_2pwm.xml - 0x0109
https://asksinpp.de/rftypes/rf_dw.xml - 0x0108

**Comment by psi-4ward** [comment]
interesting! so we can adopt the naming from there.
should I prepare a PR or would you just add the INO files?

**Comment by pa-pa** [comment]
A PR would be nice :-)

**Comment by psi-4ward** [comment]
#105

**Comment by psi-4ward** [comment]
Oh think we could close this by #105
