### ISSUE TITLE
HM-RC-8 not working properly

### ISSUE THREAD

**Issue by KoenigTH** [pa-pa/AskSinPP#41]
Hello pa-pa, I flashed my arduino pro mini (with CC1101 module) with your V3 HM-RC-8. Everything looks fine. The Device could be connected to my Raspberrymatic. I changed every channel transmission from secured to default. For testing I didn't connect all of the buttons, just button 1 (Pin 14) and button 2 (Pin 3) to Ground).

I enabled logging but the log shows nothing, desn't matters how often I pressed the buttons. 

When I flash the HM-RC-P1 Firmware from Jerome (JP112SDL) then the Button 1 works fine.

Can you help me?

Thanks and best regards
Thorsten

![grafik](https://user-images.githubusercontent.com/29251580/40568626-0db3249a-607c-11e8-9337-d7f5eb8cff24.png)

**Comment by pa-pa** [comment]
Do you get some output on the console ?
