### ISSUE TITLE
misleading DEVID in makeota.sh (should be DEVMODEL)

### ISSUE THREAD

**Issue by harvey637** [pa-pa/AskSinPP#47]
Hi using this issue to ask for correction of README.md and makeota?.sh, makeota.html

Ifi I check the wording and meaning of the 4 items, that are written at the end of bootloader I find
in device.h:
#define OTA_CONFIG_START 0x7fe0 // start address of 16 byte config data in bootloader
#define OTA_MODEL_START  0x7ff0 // start address of 2 byte model id in bootloader
#define OTA_SERIAL_START 0x7ff2 // start address of 10 byte serial number in bootloader
#define OTA_HMID_START   0x7ffc // start address of 3 byte device id in bootloader

When I look into makeota*.sh I find:
DEVID ... written to 0x7ff0, which is named OTA_MODEL_START, 2 bytes is correct
HMID ... written to 0x7ffc0, which is named OTA_HMID_START, 3 bytes is correct
SERIAL ... written to 0x7ff2, which is named OTA_SERIAL_START, 10 bytes is correct

What BUGS me is that in other parts of asksin 
- HMID is synonym to (DeviceInfo) // Device ID.
- DEVID is synonym to (DeviceInfo) // Device model

The usage of DEVID (sounds like device id to me) ist NOT equal // Device Id from DeviceInfo struct.
Which leads to confusion :-(

Proposal:
replace DEVID in makeota*.sh to DEVMODEL, errmsg should read "Wrong Device Model: 2 Byte (hex) expected"

correct type:  exprected -> expected

explain usage (meaning) of DEVMODEL, what is it good for?

adopt README.md and makeota.html accordingly

Thank You!

**Comment by pa-pa** [comment]
You are welcome to provide a PullRequest :-)

**Comment by harvey637** [comment]
Done so!

I am not shure about a place to list known "DeviceModel"s. Inside some Files in NewAskSin I found
some  Information, also I see the link from this hex value into the images used in the homematic webui.
JP has written an addon. May be this info should be part of the future documentation project of AskSinPP.

**Comment by harvey637** [comment]
It looks like confusion, wherever I look, lets try to sort it out.

originating from Device.h:

_DeviceID_ is the 3 byte hex serial/address/id of the device (important, unique to every hardware): 
change HMID to **DeviceID** in Device.h and bootloader-files and readme  (and everywhere?)
Other discussable name: **HMAddress**

_Serial_ is the ascii serial (important, unique to every hardware, change to **DeviceSerial** to clarify?)
Other discussable name: **HMSerial**

_DeviceModel_ is the 2 bye hex code, that identifies a hardware, used multiple times, corresponds to device.xml (Inconsistantly used DeviceID (jp112sdl in his addons) or HM_TYPE in bootloader.c)
Inside the device.xml it is e.g <type> .... const_value="0xf331"/>
My proposal: **DeviceType**
Other discussable name: **HMType**

_DeviceType_ is 1 byte, a simple table like "PushButton", "ThreeStateSensor"... (used multiple times, corresponds to hardware or function of a device, used near channels?)
Change to DeviceFunction? DeviceUsage? DeviceSubType?
My proposal: **DeviceSubType**
Other discussable name: **HMSubType**

Before I do the modifications inside pull-request we should all agree on naming convention,
especially in Devices.h and *ino. No code is changed, only names to clarify.

**Comment by pa-pa** [comment]
Do you really think that the names are so a big problem? I don't want to change a lot of code because the names :-( May we we add more documentation to the variables and do not change the names.
Texts in the HTML pages can be changes without any problems. Here we can also add more documentation.

**Comment by harvey637** [comment]
Hi,
please take a look into my pull-requeset, as it only deals with the bootloader.

Good and correct variable names are part of a documentation - which is still kind of growing :-)
Comparing bootloader to asksinpp (the library being the importent part) the usage of DEVID in makeota.sh and html and readme.md really is in contrast to DeviceID in asksinpp.
Yes, as I think an DEVID sounds "unique" to me, and I read a lot more in asksinpp than in bootloader.
So Yes, variable name in bootloader should be corrected (as I did in pull-request).
At lot of clarification was needed in other forums (e.g. more than one sensor with equal firmware).
Other renamings are only to make things a bit more selfexplaining - forget about it or keep in mind for V5.
Beside this every documentation is welcome. I am only slowly dive into the secrets of writing
device.xml, where the relation to this DeviceModel is most important. And what about the DeviceType?
Can a "Switch" (DeviceType 0x10) also be a PushButton (0x43)? Just some questtions from a long list.

Thank you for looking into this
harvey
