### ISSUE TITLE
Basic Module for sending 32 bit word

### ISSUE THREAD

**Issue by oskarn97** [pa-pa/AskSinPP#76]
Hey!
I am looking to build a low power sensor using Arduino Pro Mini and a CC1101 module.
All I need to do is to be able to send and receive a 32bit datagram using fhem.
Can you help me with that?

Best

**Comment by pa-pa** [comment]
You can use the generic sensor https://github.com/pa-pa/AskSinPP/tree/master/examples/custom/HB-GEN-SENS
Documentation how to integrate into FHEM can be found her https://forum.fhem.de/index.php/topic,57486.msg804110.html#msg804110
