### ISSUE TITLE
Platformio: wrong lib version

### ISSUE THREAD

**Issue by psi-4ward** [pa-pa/AskSinPP#79]
Seems like your platformio manifest is outdated:
https://platformio.org/lib/show/2900/AskSinPP/manifest
`version=2.1.5`
but 
`#define ASKSIN_PLUS_PLUS_VERSION "3.1.1"`

https://github.com/pa-pa/AskSinPP/blob/master/library.properties#L2

**Comment by pa-pa** [comment]
fixed
