### ISSUE TITLE
pwmtable starts at 1?

### ISSUE THREAD

**Issue by psi-4ward** [pa-pa/AskSinPP#80]
I've drafted the Dim1PWM 

![dim1-fritzing](https://user-images.githubusercontent.com/1191572/47670089-ae4deb00-dbac-11e8-8fa0-aaff6daeefae.png)

And uploaded `HM-LC-Dim1PWM-CV.ino`

* LED Strip is off on power on
* Dimming between 10-100% works as expected
BUT when I dimm to 0% the LEDs are still glowing cause the GPIO still emits.

When I alter the [pwmtable](https://github.com/pa-pa/AskSinPP/blob/master/actors/PWM.h#L15) to start from 0 it works as expected.

Is this a Bug or am I doing smth wrong?

**Comment by pa-pa** [comment]
This was a bug. Code changed to ensure LED off when value is 0%.

**Comment by psi-4ward** [comment]
Thanks for your fast answer! 
But the changes aren't pushed yet, are they?

**Comment by pa-pa** [comment]
You are right. They are pushed now.

**Comment by psi-4ward** [comment]
2871c681c0735f2dc2babd11386586903035135d

Perfect thanks.
