### ISSUE TITLE
Switch: Info Message auch an MasterID

### ISSUE THREAD

**Issue by jp112sdl** [pa-pa/AskSinPP#88]
**IST-Zustand:**
Wird ein Switch mittels internem self-peer Taster geschaltet, wird diese Info nur an sich selbst (Empfänger = Sender) geschickt.
```
-> 0B 02 22 40 123456 123456 01 02
<- 0E 02 80 02 123456 123456 01 01 C8 00 57
```
**SOLL-Zustand:**
Wird ein Switch mittels internem self-peer Taster geschaltet, so muss der Schaltzustand BIDI zur Zentrale übertragen werden.
Ist das Device mit keiner Zentrale gepairt, wird der Schaltzustand BCAST an `000000` gesendet.

*Schalten eines originalen HM Zwischensteckers:*
```
AUS:
ignore 0D 4C A4 10 4B2FEB 2BE14D 06 01 00 00
ignore 0A 4C 80 02 2BE14D 4B2FEB 00

EIN:
ignore 0D 4F A4 10 4B2FEB 2BE14D 06 01 C8 00
ignore 0A 4F 80 02 2BE14D 4B2FEB 00
```

**Comment by pa-pa** [comment]
fixed
